server:
  port: 8081
eureka:
  client:
    instance:
      prefer-ip-address: true
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/customer?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/ecommerceapp