eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${}:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false