server:
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /$\{segment}
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/ecommerce-app/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9080/realms/ecommerce-app
        registration:
          keycloak:
            provider: keycloak
            client-id: cloud-gateway
            client-secret: nnSi2ZoKHZO2k31flZvRZVS74LPi8595
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/auth/callback"
            scope: openid
  data:
    redis:
      host: localhost
      port: 6379
      password: admin
logging:
  level:
    org.springframework.security.oauth2: TRACE
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.data.redis: DEBUG